services:
#    code_spanish_my_movies.example:
#        class: CodeSpanish\Bundle\MyMoviesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  wikipedia:
    class: CodeSpanish\Bundle\MyMoviesBundle\Service\Wikipedia
